In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
import math
import os
import os.path
import time
import zipfile
import sqlite3

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import plotnine as pn
import scipy
import pycwt

from shoreshop3_analysis import data

In [11]:
input_coastsat = data.load_coastsat_all()
input_coastsat

                   date     x   transect
0   1984-03-24 15:13:04  73.9  0001_0001
1   1984-05-07 15:15:23  73.8  0001_0001
2   1984-06-08 15:16:13  73.7  0001_0001
3   1984-06-24 15:16:28  70.1  0001_0001
4   1984-08-27 15:18:04  66.4  0001_0001
..                  ...   ...        ...
544 2025-10-24 15:41:17  40.4  0049_0230
545 2025-11-01 15:41:22  40.6  0049_0230
546 2025-11-25 15:41:22  42.6  0049_0230
547 2025-12-11 15:41:20  41.0  0049_0230
548 2026-01-12 15:41:11  44.5  0049_0230

[6593786 rows x 3 columns]

In [12]:
print('average transect length:', len(input_coastsat) / len(input_coastsat['transect'].unique()))

average transect length: 688.3584925357553

In [14]:
models = data.MultiProfileModels(scratchdir='/scratch')
models.populate(progress=True)
#print(models._conn.execute('select count(*) from data').fetchone()[0])
# 278799708 rows

Parsing model 16/17: UNSW-WRL-Mao....ps...nce..._bruun_ssp585...
Parsed all models in 293.569 ms
278799708

In [17]:
start = time.perf_counter_ns()

df = models.load_model_transect_data('IdSOR', '0001_0001')

elapsed = time.perf_counter_ns() - start
print(f'{elapsed/1e6:.3f} ms')

df

29.877 ms

       model   transect        date     x
0      IdSOR  0001_0001  1980-01-01  None
1      IdSOR  0001_0001  1980-01-02  None
2      IdSOR  0001_0001  1980-01-03  None
3      IdSOR  0001_0001  1980-01-04  None
4      IdSOR  0001_0001  1980-01-05  None
...      ...        ...         ...   ...
16066  IdSOR  0001_0001  2023-12-27  None
16067  IdSOR  0001_0001  2023-12-28  None
16068  IdSOR  0001_0001  2023-12-29  None
16069  IdSOR  0001_0001  2023-12-30  None
16070  IdSOR  0001_0001  2023-12-31  None

[16071 rows x 4 columns]