In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import plotnine as pn

In [9]:
df = pd.read_csv('../model-trends.csv')
df

           model   transect  model_trend  coastsat_trend
0           BRIE  0032_0025     4.100930        0.000315
1           BRIE  0032_0035     3.166371       -0.000503
2           BRIE  0032_0045     2.497914       -0.000572
3           BRIE  0032_0055     2.049683       -0.000713
4           BRIE  0032_0065     1.443058       -0.001735
...          ...        ...          ...             ...
38340  Traboulsi  0049_0191     0.004197        0.003145
38341  Traboulsi  0049_0201     0.003265        0.001736
38342  Traboulsi  0049_0211     0.001961       -0.000335
38343  Traboulsi  0049_0221     0.000652       -0.001409
38344  Traboulsi  0049_0229    -0.000170       -0.001402

[38345 rows x 4 columns]

In [10]:
df.describe()

        model_trend  coastsat_trend
count  3.834000e+04    38345.000000
mean   2.549330e+09       -0.000497
std    2.232254e+11        0.004786
min   -8.094513e+03       -0.037045
25%   -2.630074e-03       -0.002408
50%   -1.368373e-04       -0.000030
75%    1.748817e-03        0.001842
max    1.954823e+13        0.025645

In [13]:
len(df[df['model_trend'] > 1])

33

In [14]:
df = df[df['model_trend'] < 1]

In [15]:
df['se'] = (df['model_trend'] - df['coastsat_trend']) ** 2
df.drop(columns=['model_trend', 'coastsat_trend', 'transect']).groupby('model').mean().rename(columns={'se': 'mse'})

                                       mse
model
BRIE                          3.489100e+00
CCOST.DESM.recon              9.711258e-06
COCollective                  5.799209e-06
CRCHI.ACC585                  5.086457e-06
CRCHI.ECE245                  6.789749e+04
CRCHI.ECE245TC                6.789749e+04
CRCHI.ECE585                  5.086457e-06
CRCHI.ECE585TC                5.086457e-06
CRCHI.IPSL245                 6.789749e+04
CRCHI.IPSL585                 5.086457e-06
CRCHI.MIR245                  6.789749e+04
CRCHI.MIR585                  5.086457e-06
CRCHI.MPI245                  6.789749e+04
CRCHI.MPI585                  5.086457e-06
CRCHI.ens                     3.990413e-05
Calcraft.MTFB                 2.992973e-06
CoSMoS.CSat                   2.900410e-06
CoSMoS.CSatBruun.245          4.754801e-06
CoSMoS.CSatBruun.585          4.767786e-06
CoSMoS.DSAS                   6.902049e-05
CoSMoS.Vit24                  3.800045e-06
CoSMoS.conv                   2.612184e-06
CoSMoS.conv.ACC245            2.620769e-06
CoSMoS.conv.ACC585            2.622399e-06
CoSMoS.conv.ECE245            2.620363e-06
CoSMoS.conv.ECE245TC          2.622176e-06
CoSMoS.conv.ECE585            2.620623e-06
CoSMoS.conv.ECE585TC          2.621196e-06
CoSMoS.conv.IPSL245           2.620084e-06
CoSMoS.conv.IPSL585           2.620488e-06
CoSMoS.conv.MIR245            2.619491e-06
CoSMoS.conv.MIR585            2.620309e-06
CoSMoS.conv.MPI245            2.619216e-06
CoSMoS.conv.MPI585            2.620261e-06
CoSMoS.convIA                 1.162888e-05
CoSMoS.persistence            2.252670e-05
Devoe.CUDEMslope              4.172048e-06
GeoOcean.xeps.bulkSLPQs.part  1.231296e-05
Holzenthal.GENCADE            1.514170e-06
ICM-TCN.eof                   1.162152e-06
IdSOR                         1.857354e-05
Mao.GraphShore                1.760483e-06
Traboulsi                     4.059276e-07

In [19]:
models = []
r2s = []
for model in df['model'].unique():
    sub = df[df['model'] == model]
    x = sub['coastsat_trend'].values
    y = sub['model_trend'].values
    a, b = np.polyfit(x, y, 1)
    yhat = x * a + b
    ss_res = ((y - yhat) ** 2).sum()
    ss_tot = ((y - y.mean()) ** 2).sum()
    r2 = 1 - ss_res / ss_tot
    models.append(model)
    r2s.append(r2)

regs = pd.DataFrame({'model': models, 'R2': r2s})
regs.to_csv('../model-trend-regs.csv')
regs

                           model        R2
0                           BRIE  0.066546
1               CCOST.DESM.recon  0.601033
2               Devoe.CUDEMslope  0.843207
3             Holzenthal.GENCADE  0.435775
4                   COCollective  0.861299
5                      CRCHI.ens  0.320072
6                   CRCHI.ECE245  0.000431
7                 CRCHI.ECE245TC  0.000431
8                  CRCHI.IPSL245  0.000431
9                   CRCHI.MIR245  0.000431
10                  CRCHI.MPI245  0.000431
11                  CRCHI.ACC585  0.791322
12                  CRCHI.ECE585  0.791322
13                CRCHI.ECE585TC  0.791322
14                 CRCHI.IPSL585  0.791322
15                  CRCHI.MIR585  0.791322
16                  CRCHI.MPI585  0.791322
17                  CoSMoS.Vit24  0.852031
18                 CoSMoS.convIA  0.678230
19                   CoSMoS.conv  0.889592
20            CoSMoS.conv.ACC245  0.889355
21            CoSMoS.conv.ACC585  0.889293
22            CoSMoS.conv.ECE245  0.889374
23          CoSMoS.conv.ECE245TC  0.889305
24            CoSMoS.conv.ECE585  0.889369
25          CoSMoS.conv.ECE585TC  0.889344
26           CoSMoS.conv.IPSL245  0.889385
27           CoSMoS.conv.IPSL585  0.889369
28            CoSMoS.conv.MIR245  0.889412
29            CoSMoS.conv.MIR585  0.889378
30            CoSMoS.conv.MPI245  0.889423
31            CoSMoS.conv.MPI585  0.889376
32                   CoSMoS.CSat  0.892697
33          CoSMoS.CSatBruun.245  0.892788
34          CoSMoS.CSatBruun.585  0.892782
35                   CoSMoS.DSAS  0.123766
36            CoSMoS.persistence  0.031386
37  GeoOcean.xeps.bulkSLPQs.part  0.599840
38                   ICM-TCN.eof  0.929102
39                         IdSOR  0.253394
40                 Calcraft.MTFB  0.893380
41                Mao.GraphShore  0.936344
42                     Traboulsi  0.893372